version: "3.8"

services:
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_LOG__CONSOLE=both
      - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=debug
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
  redis:
    image: "redis:alpine"
  api:
    build: ./api
    depends_on:
      - mqtt
      - redis
    volumes:
      - ./api:/api
    ports:
      - "80:80"
  controller:
    build: ./ctrl
    depends_on:
      - mqtt
      - redis
    volumes:
      - ./ctrl:/ctrl
    
volumes:
  api-volume:
  ctrl-volume:
