version: "3.8"

services:
  mqtt:
    image: "vernemq/vernemq"
    ports:
      - "1883:1883"
      - "8080:8080"
      - "9000:9000"
      - "9001:9001"
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_LOG__CONSOLE=both
      - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=debug
  redis:
    image: "redis:alpine"
  api:
    build: ./api
    depends_on:
      - mqtt
      - redis
    volumes:
      - ./api:/api
    ports:
      - "80:80"
  controller:
    build: ./ctrl
    depends_on:
      - mqtt
      - redis
    volumes:
      - ./ctrl:/ctrl
    
volumes:
  api-volume:
  ctrl-volume:
